#!/usr/bin/env python2.7

import googlemaps
import json
from sys import stdin

gmaps = googlemaps.Client(key='AIzaSyDeO_-gI8ENVn3QpURgH7tQdkEUk07g3ds')
for query in stdin:
    places = gmaps.geocode(query)
    print 'Latitude\tLongitude\tAddress'
    for place in places:
        latitude = None
        longitude = None
        address = None
        if 'geometry' in place:
            geometry = place['geometry']
            if 'location' in geometry:
                location = geometry['location']
                if 'lat' in location:
                    latitude = location['lat']
                if 'lng' in location:
                    longitude = location['lng']
        if 'formatted_address' in place:
            address = place['formatted_address']
        if latitude and longitude and address: 
            print str(latitude) + '\t' + str(longitude) + '\t' + address
