#!/usr/bin/env python2.7

import fileinput
import googlemaps
from googlemaps.places import places_nearby
import mgrs

map_client = googlemaps.Client(key='AIzaSyDeO_-gI8ENVn3QpURgH7tQdkEUk07g3ds')
converter = mgrs.MGRS()
boise = (43.6007205, -116.3739816)
for query in fileinput.input():
    response = places_nearby(client=map_client, location=boise, keyword=query, rank_by='distance')
    print 'MGRS\tName\tAddress'
    if 'results' in response:
        results = response['results']
        for result in results:
            name = None
            address = None
            latitude = None
            longitude = None
            if 'name' in result:
                name = result['name']
            if 'vicinity' in result:
                address = result['vicinity']
            if 'geometry' in result:
                geometry = result['geometry']
            if 'location' in geometry:
                location = geometry['location']
                if 'lat' in location:
                    latitude = location['lat']
                if 'lng' in location:
                    longitude = location['lng']
            if name and address and latitude and longitude:
                mgrs_point_raw = converter.toMGRS(latitude, longitude, 10)
                if mgrs_point_raw and len(mgrs_point_raw) >= 14:
                    zone = mgrs_point_raw[:-12]
                    square = mgrs_point_raw[-12:-10]
                    easting = mgrs_point_raw[-10:-6]
                    northing = mgrs_point_raw[-5:-1]
                    mgrs_point = zone + ' ' + square + ' ' + easting + ' ' + northing
                    print mgrs_point + '\t' + name + '\t' + address
